# AUTO-GENERATED by gen_app_registry.py — do not edit by hand.
# Re-run: python3 app/tools/gen_app_registry.py

APP_ORDER = ['Spotify', 'Clock', 'Weather', 'Crypto', 'Matrix', 'Life', 'Stock', 'Aquarium', 'Teletext', 'PlaneRadar', 'Settings', 'WebRadio', 'LocalPlayer']
APP_SLOT  = {name: i for i, name in enumerate(APP_ORDER)}
CONFIGURABLE = {"Aquarium", "Clock", "Crypto", "Life", "Matrix", "PlaneRadar", "Spotify", "Stock", "Teletext", "WebRadio"}
DISPLAY = {'Spotify': 'Winamp', 'Clock': 'Clock', 'Weather': 'Weather', 'Crypto': 'Crypto', 'Matrix': 'Matrix', 'Life': 'Life', 'Stock': 'Stock', 'Aquarium': 'Aquarium', 'Teletext': 'Teletext', 'PlaneRadar': 'PlaneRadar', 'Settings': 'Settings', 'WebRadio': 'WebRadio', 'LocalPlayer': 'Player'}
APP_COUNT = 13
