# AUTO-GENERATED by gen_app_registry.py — do not edit by hand.
# Re-run: python3 app/tools/gen_app_registry.py

APP_ORDER = ['Spotify', 'Clock', 'Weather', 'Crypto', 'Matrix', 'Life', 'Settings', 'Stock', 'Aquarium', 'Teletext', 'WebRadio']
APP_SLOT  = {name: i for i, name in enumerate(APP_ORDER)}
CONFIGURABLE = {"Aquarium", "Clock", "Crypto", "Life", "Matrix", "Stock", "Teletext"}
APP_COUNT = 11
