#!/usr/bin/env python3
"""bake_airports.py — M-PLANERADAR: bake OurAirports runway DB (ADR-049).

Adopts pr_airport_bake_trial.py's selection logic (host/pr_airport_bake_trial.py:
large_airport class, non-helipad runways with both endpoints resolved) into
this project's bake-script conventions: app/gen/ output, golden.sha256
determinism gate (ADR-008 pattern), --bbox/--center-radius-km parameterised
with V-europe (lat 35..62, lon -11..30) as the ADR-049 committed default.

Design: docs/architecture/designs/M-PLANERADAR/phase0-airport-db.md
Decision: docs/architecture/decisions/ADR-049.md

Usage:
  ~/proj/esp/venv/bin/python3 app/tools/bake_airports.py
  python3 app/tools/bake_airports.py --bbox 35,62,-11,30
  python3 app/tools/bake_airports.py --center-radius-km 52.3676,4.9041,500
"""
from __future__ import annotations

import argparse
import csv
import io
import math
import sys
import urllib.request
from pathlib import Path

# Pinned OurAirports commit (resolved 2026-07-11) — refreshing this is a
# deliberate, reviewed bump (phase0-airport-db.md's adoption plan); "main"
# would break the golden.sha256 determinism gate on every upstream edit.
DEFAULT_COMMIT = "d5773e182feeb74dcb3a34969523beea259683c4"
BASE = "https://raw.githubusercontent.com/davidmegginson/ourairports-data/{commit}/"

DEFAULT_BBOX = (35.0, 62.0, -11.0, 30.0)   # ADR-049 V-europe: lat_min,lat_max,lon_min,lon_max
DEFAULT_CLASSES = ("large_airport",)


def fetch_csv(url: str) -> list[dict[str, str]]:
    with urllib.request.urlopen(url, timeout=120) as resp:
        text = resp.read().decode("utf-8")
    return list(csv.DictReader(io.StringIO(text)))


# --- selection logic (ported verbatim from pr_airport_bake_trial.py) --------
def is_h_designator(s: str) -> bool:
    if not s or s[0] != "H":
        return False
    rest = s[1:]
    if not rest or rest[0] in "-_":
        return True
    return rest.isdigit()


def is_helipad(row: dict[str, str]) -> bool:
    le = (row.get("le_ident") or "").strip().upper()
    he = (row.get("he_ident") or "").strip().upper()
    if not is_h_designator(le) and not is_h_designator(he):
        return False
    try:
        length_ft = int(row.get("length_ft") or 0)
    except ValueError:
        length_ft = 0
    if is_h_designator(le) and is_h_designator(he):
        return True
    return length_ft < 2500


def runway_ok(row: dict[str, str]) -> bool:
    if (row.get("closed") or "0").strip() == "1":
        return False
    if is_helipad(row):
        return False
    for k in ("le_latitude_deg", "le_longitude_deg",
              "he_latitude_deg", "he_longitude_deg"):
        v = row.get(k)
        if not v or not v.strip():
            return False
    return True


def haversine_km(a: tuple[float, float], b: tuple[float, float]) -> float:
    lat1, lon1, lat2, lon2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    h = (math.sin((lat2 - lat1) / 2) ** 2
         + math.cos(lat1) * math.cos(lat2) * math.sin((lon2 - lon1) / 2) ** 2)
    return 2 * 6371.0 * math.asin(math.sqrt(h))


def select(airports_rows, runways_rows, classes: tuple[str, ...], pred):
    """Return airports (ICAO-sorted) matching classes+pred with >=1 kept runway."""
    aps: dict[str, dict] = {}
    for row in airports_rows:
        if (row.get("type") or "").strip() not in classes:
            continue
        ident = (row.get("ident") or "").strip()
        if len(ident) != 4:
            continue
        try:
            lat = float(row["latitude_deg"])
            lon = float(row["longitude_deg"])
        except (KeyError, ValueError):
            continue
        if not pred(lat, lon):
            continue
        aps[ident] = {"ident": ident, "lat": lat, "lon": lon, "runways": []}
    for row in runways_rows:
        ident = (row.get("airport_ident") or "").strip()
        if ident in aps and runway_ok(row):
            aps[ident]["runways"].append((
                float(row["le_latitude_deg"]), float(row["le_longitude_deg"]),
                float(row["he_latitude_deg"]), float(row["he_longitude_deg"]),
            ))
    return sorted((a for a in aps.values() if a["runways"]), key=lambda a: a["ident"])


# --- C emission --------------------------------------------------------------
def emit(airports: list[dict], commit: str, out_dir: Path) -> tuple[int, int]:
    total_runways = sum(len(a["runways"]) for a in airports)

    header = [
        "// AUTO-GENERATED by app/tools/bake_airports.py — do not edit by hand.",
        f"// Re-run: ~/proj/esp/venv/bin/python3 app/tools/bake_airports.py --commit {commit}",
        "// M-PLANERADAR runway overlay DB (ADR-049: V-europe bbox, large_airport class).",
        f"// Source: davidmegginson/ourairports-data @ {commit}",
        "#pragma once",
        "#include <stdint.h>",
        "",
        # typedef struct (not a bare struct tag) — this header is included from
        # a plain-C translation unit (planeradar_airports.c compiles as C, like
        # skin_assets.c/skin_layout.h's SkinUV precedent), where a bare tag name
        # isn't usable as a type without the `struct` keyword.
        "typedef struct { float leLat, leLon, heLat, heLon; } PrRunwayRec;",
        "typedef struct { char icao[5]; uint16_t rwOffset, rwCount; float lat, lon; } PrAirportRec;",
        "",
        f"#define PR_AIRPORT_COUNT {len(airports)}",
        f"#define PR_RUNWAY_COUNT {total_runways}",
        "",
        "extern const PrRunwayRec  kPrRunways[PR_RUNWAY_COUNT];",
        "extern const PrAirportRec kPrAirports[PR_AIRPORT_COUNT];",
        "",
    ]
    (out_dir / "planeradar_airports.h").write_text("\n".join(header))

    body = [
        "// AUTO-GENERATED by app/tools/bake_airports.py — do not edit by hand.",
        '#include "planeradar_airports.h"',
        "",
        "const PrRunwayRec kPrRunways[PR_RUNWAY_COUNT] = {",
    ]
    airport_lines = []
    offset = 0
    for a in airports:
        for le_lat, le_lon, he_lat, he_lon in a["runways"]:
            body.append(f"    {{ {le_lat:.6f}f, {le_lon:.6f}f, {he_lat:.6f}f, {he_lon:.6f}f }},")
        airport_lines.append(
            f'    {{ "{a["ident"]}", {offset}, {len(a["runways"])}, {a["lat"]:.6f}f, {a["lon"]:.6f}f }},'
        )
        offset += len(a["runways"])
    body.append("};")
    body.append("")
    body.append("const PrAirportRec kPrAirports[PR_AIRPORT_COUNT] = {")
    body.extend(airport_lines)
    body.append("};")
    body.append("")
    (out_dir / "planeradar_airports.c").write_text("\n".join(body))

    return len(airports), total_runways


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--commit", default=DEFAULT_COMMIT)
    p.add_argument("--bbox", default=None,
                    help="lat_min,lat_max,lon_min,lon_max (default: ADR-049 V-europe)")
    p.add_argument("--center-radius-km", default=None,
                    help="lat,lon,radius_km — alternative to --bbox")
    p.add_argument("--classes", default=",".join(DEFAULT_CLASSES))
    p.add_argument("--out-dir", default=None)
    args = p.parse_args()

    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent
    out_dir = Path(args.out_dir) if args.out_dir else (repo_root / "app" / "gen")
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.center_radius_km:
        clat, clon, rad = (float(x) for x in args.center_radius_km.split(","))
        pred = lambda lat, lon: haversine_km((lat, lon), (clat, clon)) <= rad
    else:
        lat_min, lat_max, lon_min, lon_max = (
            tuple(float(x) for x in args.bbox.split(",")) if args.bbox else DEFAULT_BBOX
        )
        pred = lambda lat, lon: lat_min <= lat <= lat_max and lon_min <= lon <= lon_max

    classes = tuple(c.strip() for c in args.classes.split(",") if c.strip())

    base = BASE.format(commit=args.commit)
    print(f"fetching OurAirports CSVs @ {args.commit} ...", file=sys.stderr)
    airports_rows = fetch_csv(base + "airports.csv")
    runways_rows = fetch_csv(base + "runways.csv")
    print(f"airports.csv rows={len(airports_rows)} runways.csv rows={len(runways_rows)}",
          file=sys.stderr)

    airports = select(airports_rows, runways_rows, classes, pred)
    n_ap, n_rw = emit(airports, args.commit, out_dir)
    print(f"wrote {out_dir}/planeradar_airports.{{c,h}} — {n_ap} airports, {n_rw} runways")
    return 0


if __name__ == "__main__":
    sys.exit(main())
