#!/usr/bin/env python3
"""
gen_mem_layout.py — read app/mem_manifest.yaml and emit:
  app/gen/mem_layout.h   (C header: static overlay arrays + MEM_* macros + budget constants)
  app/gen/mem_layout.py  (Python mirror for the test suite)

Algorithm (M-MEMPLAN §4):
  group buffers by (caps, group) — sorted for determinism
  for each (caps, group):
      per-app working-set = SUM of that app's buffer sizes  (coexist within app)
      region_size = MAX over apps                            (mutually exclusive across apps → overlay)
      assign per-app contiguous offsets [0 .. app_sum)
  for each caps in ceiling:
      assert SUM(region_sizes) + headroom[caps] <= ceiling[caps]  — HARD non-zero exit on overflow
  emit deterministic outputs (sorted iteration throughout)

Invariant (§4b): kind=state is rejected from any group that has >1 app.

Run:
  python3 app/tools/gen_mem_layout.py
  python3 app/tools/gen_mem_layout.py --out-dir /tmp/foo   # staleness check (check_build.sh [6/6])
"""

import argparse
import pathlib
import sys
from collections import defaultdict

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML not installed — pip install pyyaml")


BANNER_H = "// AUTO-GENERATED by gen_mem_layout.py — do not edit; re-run: python3 app/tools/gen_mem_layout.py\n// Source: app/mem_manifest.yaml\n"
BANNER_PY = "# AUTO-GENERATED by gen_mem_layout.py — do not edit; re-run: python3 app/tools/gen_mem_layout.py\n# Source: app/mem_manifest.yaml\n"


def load_manifest(path: pathlib.Path) -> dict:
    with path.open() as f:
        data = yaml.safe_load(f)
    if "buffers" not in data:
        sys.exit(f"ERROR: manifest {path} has no 'buffers' key")
    return data


def plan(manifest: dict) -> dict:
    """Run the M-MEMPLAN §4 algorithm. Returns layout dict."""
    buffers = manifest["buffers"]
    ceiling = manifest.get("ceiling", {})
    headroom = manifest.get("headroom", {})

    # group buffers by (caps, group) — sorted
    groups: dict[tuple, list] = defaultdict(list)
    for b in buffers:
        groups[(b["caps"], b["group"])].append(b)

    # §4b invariant: kind=state rejected from multi-app groups
    for (caps, grp), bufs in sorted(groups.items()):
        apps_in_group = {b["app"] for b in bufs}
        if len(apps_in_group) > 1:
            for b in bufs:
                if b.get("kind") == "state":
                    sys.exit(
                        f"ERROR: §4b violation — buffer '{b['name']}' (kind=state) is in "
                        f"group '{grp}' which has {len(apps_in_group)} apps "
                        f"({', '.join(sorted(apps_in_group))}). "
                        "Only 'scratch' may be in multi-app overlay groups."
                    )

    # per-group layout
    region_layout = {}   # (caps, group) → {region_size, per_app: {app: [(name, offset, size)]}}
    budget_by_caps: dict[str, int] = defaultdict(int)

    for (caps, grp), bufs in sorted(groups.items()):
        # per-app working-set sums
        app_bufs: dict[str, list] = defaultdict(list)
        for b in bufs:
            app_bufs[b["app"]].append(b)
        app_sums = {app: sum(b["size"] for b in bs) for app, bs in sorted(app_bufs.items())}
        region_size = max(app_sums.values())

        # assign contiguous offsets within each app's slice
        per_app: dict[str, list] = {}
        for app in sorted(app_bufs.keys()):
            offset = 0
            placements = []
            for b in app_bufs[app]:
                placements.append({"name": b["name"], "offset": offset, "size": b["size"]})
                offset += b["size"]
            per_app[app] = placements

        region_layout[(caps, grp)] = {
            "region_size": region_size,
            "app_sums": app_sums,
            "per_app": per_app,
        }
        budget_by_caps[caps] += region_size

    # WCMU budget gate
    for caps in sorted(ceiling.keys()):
        used = budget_by_caps.get(caps, 0)
        head = headroom.get(caps, 0)
        cap = ceiling[caps]
        if used + head > cap:
            sys.exit(
                f"ERROR: WCMU budget overflow — {caps} overlay {used} B + "
                f"headroom {head} B = {used + head} B > ceiling {cap} B "
                f"(overflow by {used + head - cap} B). "
                "Reduce a buffer size or raise the ceiling in app/mem_manifest.yaml."
            )

    return {
        "region_layout": region_layout,
        "budget_by_caps": dict(budget_by_caps),
        "ceiling": ceiling,
        "headroom": headroom,
    }


def emit_c_header(layout: dict, out_path: pathlib.Path) -> None:
    region_layout = layout["region_layout"]
    budget = layout["budget_by_caps"]

    lines = [BANNER_H, "#pragma once", "#include <stdint.h>", ""]

    for (caps, grp) in sorted(region_layout.keys()):
        info = region_layout[(caps, grp)]
        region_size = info["region_size"]
        app_sums = info["app_sums"]
        per_app = info["per_app"]

        sym = f"s_overlay_{caps.lower()}_{grp.lower()}"
        dominant = max(app_sums, key=lambda a: app_sums[a])
        lines.append(
            f"/* region: {caps} / {grp} — {region_size} B "
            f"(max of {dominant} {app_sums[dominant]} B) */"
        )
        lines.append(
            f"static uint8_t {sym}[{region_size}] "
            f"__attribute__((aligned(4), unused));"
        )

        # emit MEM_* macros — apps sorted, buffers in placement order
        overlay_apps = sorted(per_app.keys())
        if len(overlay_apps) > 1:
            app_ranges = ", ".join(
                f"{a} @ [0, {app_sums[a]})" for a in overlay_apps
            )
            lines.append(f"/* mutually exclusive overlay: {app_ranges} */")
        for app in overlay_apps:
            for p in per_app[app]:
                lines.append(
                    f"#define MEM_{p['name']} ({sym} + {p['offset']})"
                )
        lines.append("")

    # budget summary
    lines.append("/* budget summary */")
    for caps in sorted(budget.keys()):
        lines.append(f"#define MEM_BUDGET_{caps}_USED {budget[caps]}")
    lines.append("")

    out_path.write_text("\n".join(lines))


def emit_python_mirror(layout: dict, out_path: pathlib.Path) -> None:
    region_layout = layout["region_layout"]
    budget = layout["budget_by_caps"]

    offsets = {}
    for (caps, grp), info in sorted(region_layout.items()):
        for app in sorted(info["per_app"].keys()):
            for p in info["per_app"][app]:
                offsets[p["name"]] = (caps, grp, p["offset"])

    region_sizes = {
        (caps, grp): info["region_size"]
        for (caps, grp), info in sorted(region_layout.items())
    }

    lines = [
        BANNER_PY,
        f"MEM_OFFSETS = {offsets!r}",
        f"MEM_REGION_SIZES = {region_sizes!r}",
        f"MEM_BUDGET_USED = {budget!r}",
        "",
    ]
    out_path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate mem_layout files from mem_manifest.yaml")
    parser.add_argument(
        "--out-dir",
        metavar="DIR",
        help="Write outputs to DIR instead of their canonical locations",
    )
    args = parser.parse_args()

    script_dir = pathlib.Path(__file__).parent
    repo_root = script_dir.parent.parent

    manifest_path = repo_root / "app" / "mem_manifest.yaml"
    if not manifest_path.exists():
        sys.exit(f"ERROR: {manifest_path} not found")

    manifest = load_manifest(manifest_path)
    layout = plan(manifest)

    if args.out_dir:
        out_dir = pathlib.Path(args.out_dir)
        h_path  = out_dir / "mem_layout.h"
        py_path = out_dir / "mem_layout.py"
    else:
        h_path  = repo_root / "app" / "gen" / "mem_layout.h"
        py_path = repo_root / "app" / "gen" / "mem_layout.py"

    emit_c_header(layout, h_path)
    emit_python_mirror(layout, py_path)
    print(f"wrote {h_path}")
    print(f"wrote {py_path}")

    # print budget summary to stdout
    budget = layout["budget_by_caps"]
    ceiling = layout["ceiling"]
    headroom = layout["headroom"]
    for caps in sorted(budget.keys()):
        used = budget[caps]
        head = headroom.get(caps, 0)
        cap = ceiling.get(caps, "—")
        print(f"  {caps}: overlay {used} B + headroom {head} B = {used + head} B / ceiling {cap} B")


if __name__ == "__main__":
    main()
