#!/usr/bin/env python3
"""
gen_app_registry.py — parse app/src/appRegistry.h and emit:
  app/tools/app_ids_gen.py     (Python-side mirror for the test suite)
  app/gen/configurable_apps.h  (C header for settings/appsSection.h)

Run after editing appRegistry.h:
  ~/proj/esp/venv/bin/python3 app/tools/gen_app_registry.py

check_build.sh step [5/5] runs this and diffs the output; any staleness fails
the build check.
"""

import argparse
import pathlib
import re
import sys


def parse_registry(header_path: pathlib.Path) -> list[tuple[str, str, int]]:
    """Return list of (Name, icon_char, configurable) for each active APP_X row."""
    rows = []
    pattern = re.compile(
        r"""^\s*APP_X\s*\(\s*(\w+)\s*,\s*'(.)'\s*,\s*([01])\s*\)""",
        re.ASCII,
    )
    for line in header_path.read_text().splitlines():
        # Skip commented-out rows
        stripped = line.lstrip()
        if stripped.startswith("//"):
            continue
        m = pattern.match(line)
        if m:
            rows.append((m.group(1), m.group(2), int(m.group(3))))
    return rows


def emit_python(rows: list, out_path: pathlib.Path) -> None:
    names = [r[0] for r in rows]
    configurable = sorted(r[0] for r in rows if r[2])
    configurable_repr = "{" + ", ".join(f'"{n}"' for n in configurable) + "}"
    lines = [
        "# AUTO-GENERATED by gen_app_registry.py — do not edit by hand.",
        "# Re-run: ~/proj/esp/venv/bin/python3 app/tools/gen_app_registry.py",
        "",
        f"APP_ORDER = {names!r}",
        "APP_SLOT  = {name: i for i, name in enumerate(APP_ORDER)}",
        f"CONFIGURABLE = {configurable_repr}",
        f"APP_COUNT = {len(names)}",
        "",
    ]
    out_path.write_text("\n".join(lines))


def emit_c_header(rows: list, out_path: pathlib.Path) -> None:
    configurable = [(r[0], i) for i, r in enumerate(rows) if r[2]]
    count = len(configurable)
    body_lines = [
        "// AUTO-GENERATED by gen_app_registry.py — do not edit by hand.",
        "// Re-run: ~/proj/esp/venv/bin/python3 app/tools/gen_app_registry.py",
        "#pragma once",
        f"#define CONFIGURABLE_APP_COUNT {count}",
        "static const struct { const char* name; AppId id; } kConfigurableApps[] = {",
    ]
    for name, idx in configurable:
        body_lines.append(f'    {{ "{name}", AppId::{name} }},')
    body_lines.append("};")
    body_lines.append("")
    out_path.write_text("\n".join(body_lines))


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate app registry files")
    parser.add_argument(
        "--out-dir",
        metavar="DIR",
        help="Write outputs to DIR instead of their canonical locations",
    )
    args = parser.parse_args()

    script_dir = pathlib.Path(__file__).parent
    repo_root = script_dir.parent.parent

    header_path = repo_root / "app" / "src" / "appRegistry.h"
    if not header_path.exists():
        sys.exit(f"ERROR: {header_path} not found")

    rows = parse_registry(header_path)
    if not rows:
        sys.exit("ERROR: no APP_X rows found in appRegistry.h")

    if args.out_dir:
        out_dir = pathlib.Path(args.out_dir)
        py_path = out_dir / "app_ids_gen.py"
        h_path  = out_dir / "configurable_apps.h"
    else:
        py_path = script_dir / "app_ids_gen.py"
        h_path  = repo_root / "app" / "gen" / "configurable_apps.h"

    emit_python(rows, py_path)
    emit_c_header(rows, h_path)
    print(f"wrote {py_path}")
    print(f"wrote {h_path}")


if __name__ == "__main__":
    main()
