#!/usr/bin/env python3
"""gen_countries.py — bake the committed ISO 3166-1 table into app/gen/countries.h.

M-COUNTRY-PICKER D2 (supersedes and deletes gen_webradio_countries.py, CP-2):
reads ONLY the committed input file app/tools/data/iso3166.csv — network-free
by construction (CP-3, ADR-008 #9 pattern), so re-running is byte-identical
and the output is pinned in app/gen/golden.sha256 (check_build.sh gate 3).

Output: struct CountryEntry { const char* name; const char* code; },
kCountries[] (alphabetical by name, case-insensitive) + kCountryCount
(int16_t — CP-7: 249 entries clear uint8_t by only 6).

Run after editing iso3166.csv:
  python3 app/tools/gen_countries.py
Then refresh the golden pin:
  cd app/gen && sha256sum countries.h   # update golden.sha256 line
"""

import pathlib
import sys

EXPECTED_COUNT = 249   # officially assigned ISO 3166-1 alpha-2 codes

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
CSV_PATH = REPO_ROOT / "app" / "tools" / "data" / "iso3166.csv"
OUT_H = REPO_ROOT / "app" / "gen" / "countries.h"


def parse_csv(path: pathlib.Path) -> list[tuple[str, str]]:
    """Return (name, code) rows. Format: code,name — split on the FIRST comma
    only (names may contain commas, e.g. 'Bonaire, Sint Eustatius, Saba')."""
    rows = []
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "," not in line:
            sys.exit(f"ERROR: {path}:{lineno}: no comma in row: {line!r}")
        code, name = line.split(",", 1)
        code, name = code.strip(), name.strip()
        if len(code) != 2 or not code.isalpha() or not code.isupper():
            sys.exit(f"ERROR: {path}:{lineno}: bad alpha-2 code: {code!r}")
        if not name or not name.isascii():
            sys.exit(f"ERROR: {path}:{lineno}: name must be non-empty ASCII "
                     f"(panel font has no diacritics): {name!r}")
        rows.append((name, code))
    return rows


def main() -> None:
    if not CSV_PATH.exists():
        sys.exit(f"ERROR: {CSV_PATH} not found")
    rows = parse_csv(CSV_PATH)

    codes = [c for _, c in rows]
    dupes = sorted({c for c in codes if codes.count(c) > 1})
    if dupes:
        sys.exit(f"ERROR: duplicate codes: {', '.join(dupes)}")
    if len(rows) != EXPECTED_COUNT:
        sys.exit(f"ERROR: expected {EXPECTED_COUNT} codes, got {len(rows)} — "
                 "an ISO assignment change is a deliberate, reviewed edit "
                 "(update EXPECTED_COUNT alongside the CSV)")

    rows.sort(key=lambda r: r[0].lower())

    lines = [
        "// AUTO-GENERATED by gen_countries.py — do not edit by hand.",
        "// Re-run: python3 app/tools/gen_countries.py",
        "// Source: app/tools/data/iso3166.csv (committed, network-free bake — "
        "M-COUNTRY-PICKER D2/CP-3).",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "struct CountryEntry { const char* name; const char* code; };",
        "",
        "static const CountryEntry kCountries[] = {",
    ]
    for name, code in rows:
        esc = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{ "{esc}", "{code}" }},')
    lines += [
        "};",
        "",
        "// int16_t per CP-7 — a generic picker count must not sit 6 below the",
        "// uint8_t ceiling.",
        "static constexpr int16_t kCountryCount ="
        " (int16_t)(sizeof(kCountries) / sizeof(kCountries[0]));"
        f"   // {len(rows)}",
        "",
    ]
    OUT_H.write_text("\n".join(lines))
    print(f"wrote {OUT_H} ({len(rows)} entries)")


if __name__ == "__main__":
    main()
