#!/usr/bin/env python3
"""TASK-418 / T_PLR_25 (playback half) — auto-advance end to end, on
cyd2usb_player.

Mirrors TASK-416's test_fbrowser_player.py precedent exactly (structure,
reboot/settle tolerance, port handling) — see that file's own docstring for
the TASK-425/431 background on why local playback only works on
cyd2usb_player at all. This script is the ONE real-playback id in the
TASK-418 gate: T_PLR_20-24/26 (the shuffle bag, the four end-of-list cells,
prev-history, tap-to-play cursor, persistence) never decode audio — they run
on cyd2usb_winamp_debug through the normal run_serialdbg_tests.py harness,
via the `advance`/`set plCursor`/`get plOrder` debug surface added
specifically so they don't need this script. T_PLR_25 is different: it
proves audio_eof_mp3() (which only fires on a REAL decode reaching end of
file) drives the exact same _stepOrder()/_startPlayback() path the debug
surface exercises — that can only be observed by actually playing something
to completion.

A REBOOT IS A HARD FAIL (VE, 2026-08-15). This script used to retry the
whole sequence up to MAX_ATTEMPTS times on a reboot signature, because
`aeConnectFile()`'s `new Audio(...)` could throw an uncaught bad_alloc under
transient heap pressure right after a flash (abort() -> reboot) and a retry
at settled heap succeeded cleanly. **TASK-432 fixed that** — `aeEnsureAudio()`
is now the only construction site and carries both TASK-289's 16 KB DMA floor
and `new (std::nothrow)` + a null check, so a shortfall degrades to a clean
`play FAILED`, not a reset. The retry loop therefore no longer tolerates a
known transient: it can only launder the defect under test into a green run.
Any reset signature now fails immediately, loudly, on the first occurrence.
(This is independent of TASK-443's ruling — the crash being retried past is
already fixed either way.) A `PlaybackNeverStarted`
(pump task creation / the decoder allocation failing without a crash) is NOT retried
in-process — DUT-measured (TASK-416's own script, same board): re-opening the
serial port lands inside the ESP32's double-reset-detector window and
reproduces the identical stuck state rather than a clean boot. Only a real
reflash (run/playorder-player) gets a genuinely fresh boot.

Fixture: /playlists/short5.m3u, 5 real ~3s tones (app/tools/fixtures/sd's
gen_playlist_fixtures.py generates only text — these are binary audio,
pushed once via sd_put.py, not regenerated by this script).

Usage: run/playorder-player (flashes cyd2usb_player, runs this, restores prod)
       python3 test_playorder_player.py --port /dev/ttyUSB1
"""
import argparse
import json
import pathlib
import sys
import time

import serial

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from lib.dut import resolve_port  # TASK-479: one port resolver (run/port)

PL_SHORT5 = "/playlists/short5.m3u"   # 5 real short tracks (TASK-418 fixture)

_REBOOT_MARKERS = ("ets Jul", "rst:0x", "abort() was called")


class RebootDetected(Exception):
    pass


class PlaybackNeverStarted(Exception):
    """Same class as test_fbrowser_player.py's — pump-task creation or the
    decoder allocation can fail under heap pressure that hasn't settled yet,
    without an actual crash. NOT retried in-process (see main())."""
    pass


def wait_boot(ser: serial.Serial, settle_s: float) -> None:
    print(f"waiting {settle_s:.0f}s for boot + WiFi settle...", flush=True)
    time.sleep(settle_s)
    ser.reset_input_buffer()


def cmd(ser: serial.Serial, line: str, timeout: float = 6.0) -> dict:
    """Send one command, return its JSON reply. Raises RebootDetected if a
    reboot signature appears first — the caller decides whether to tolerate
    it."""
    ser.write((line + "\n").encode())
    deadline = time.monotonic() + timeout
    last = {}
    while time.monotonic() < deadline:
        raw = ser.readline().decode(errors="replace").strip()
        if not raw:
            continue
        print(raw)
        if any(m in raw for m in _REBOOT_MARKERS):
            raise RebootDetected(raw)
        if raw.startswith("{"):
            try:
                d = json.loads(raw)
            except json.JSONDecodeError:
                continue
            last = d
            if d.get("last") or "cmd" in d:
                return d
    return last


def fail(msg: str) -> None:
    print(f"FAIL: {msg}")
    sys.exit(1)


def run_sequence(ser: serial.Serial, per_track_timeout_s: float) -> list:
    """The whole enter-player -> load -> play -> auto-advance x5 sequence,
    one shot. Returns the observed row sequence on success. Raises
    RebootDetected on a crash-reboot (the caller FAILS on it — a reset is a
    defect, not a transient) or calls fail() (via SystemExit) on any other
    real defect."""
    print("=== enter Player mode, load the 5-short-track playlist ===")
    r = cmd(ser, "set playerMode player")
    if not r.get("ok"):
        fail(f"set playerMode player failed: {r}")

    r = cmd(ser, "set bgPoll 0")
    if not r.get("ok"):
        fail(f"set bgPoll 0 failed: {r}")

    r = cmd(ser, f"set plLoad {PL_SHORT5}", timeout=15.0)
    if not r.get("ok"):
        fail(f"set plLoad {PL_SHORT5} failed (fixture missing? — see "
             f"app/tools/sd_put.py to push it): {r}")
    r = cmd(ser, "get plCount")
    if r.get("count") != 5:
        fail(f"plCount={r.get('count')} (expected 5) — fixture wrong or missing")

    # D9: shuffle off, repeat off — a clean, deterministic 0..4 sweep with a
    # real "stop, don't wrap" ending. Driven via `tap` on the sprite
    # coordinates (no dedicated debug verb — see localPlayerApp.h's sinks).
    print("=== confirm shuffle=off repeat=off (tap sprites until they read that way) ===")
    for _ in range(3):
        sr = cmd(ser, "get shufRep")
        if sr.get("lastShuffle") != 1:
            break
        cmd(ser, "tap 187 96")   # SHUFFLE_X/Y centre, see gen/skin_layout.h
        time.sleep(0.2)
    for _ in range(4):
        sr = cmd(ser, "get shufRep")
        if sr.get("lastRepeat") == 2:
            break
        cmd(ser, "tap 225 96")   # REPEAT_X/Y centre
        time.sleep(0.2)
    sr = cmd(ser, "get shufRep")
    if sr.get("lastShuffle") == 1 or sr.get("lastRepeat") != 2:
        fail(f"could not settle shuffle=off/repeat=off before playing: {sr}")

    r = cmd(ser, "set plPlay 0", timeout=10.0)
    if not r.get("ok"):
        fail(f"set plPlay 0 failed: {r}")

    print("=== waiting for row 0 to actually start playing ===")
    playing = False
    deadline = time.monotonic() + 15.0
    while time.monotonic() < deadline:
        st = cmd(ser, "get plCount", timeout=4.0)
        if st.get("playing") and st.get("curRow") == 0:
            playing = True
            break
        time.sleep(1.0)
    if not playing:
        # Same tolerance class as test_fbrowser_player.py's — see its
        # PlaybackNeverStarted docstring for the DUT-measured reasoning.
        raise PlaybackNeverStarted("plCount.playing/curRow never reached (True, 0) within 15s")
    # Do NOT claim "arena acquired" here: this script never reads arenaStats.
    # All that is actually observed is that the decode started.
    # CORRECTED 2026-08-17 (TASK-513): this comment used to add "and under
    # TASK-443's ruling the FILE arm does not acquire the arena at all". That
    # ruling was WITHDRAWN (successor TASK-452, still OPEN) and never landed, and
    # T_PMT_04 has now MEASURED the opposite on cyd2usb_player: acquires 0 -> 1
    # with active=1 during real playback, released on mode exit. A withdrawn
    # decision was being cited as fact in three places.
    print("playback confirmed — decoding row 0")

    print("=== waiting for auto-advance through all 5 short tracks ===")
    played_rows = [0]
    last_row = 0
    stopped_after_last = False
    deadline = time.monotonic() + (per_track_timeout_s * 5)
    while time.monotonic() < deadline:
        time.sleep(0.5)
        st = cmd(ser, "get plCount", timeout=4.0)
        if not st.get("ok"):
            fail(f"DUT stopped responding mid-playback: {st}")
        cur = st.get("curRow")
        if cur is not None and cur >= 0 and cur != last_row:
            played_rows.append(cur)
            last_row = cur
        if last_row == 4 and not st.get("playing") and len(played_rows) >= 1:
            # Row 4 (the last) finished and nothing followed — repeat is
            # off, so this is the expected end (design §8: "shuffle off,
            # repeat off -> stop at last row"), not a hang.
            stopped_after_last = True
            break

    if played_rows != [0, 1, 2, 3, 4]:
        fail(f"row sequence {played_rows} != [0, 1, 2, 3, 4]")
    if not stopped_after_last:
        fail(f"did not observe playback stop after row 4 within "
             f"{per_track_timeout_s * 5:.0f}s — sequence so far: {played_rows}")

    return played_rows


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", default=resolve_port())
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--settle-s", type=float, default=90.0)
    ap.add_argument("--per-track-timeout-s", type=float, default=15.0,
                     help="ceiling per track (3s tone + connect/decode overhead)")
    args = ap.parse_args()

    ser = serial.Serial(args.port, args.baud, timeout=1.0)
    ser.dtr = False
    ser.rts = False
    time.sleep(0.3)
    wait_boot(ser, args.settle_s)

    try:
        played_rows = run_sequence(ser, args.per_track_timeout_s)
    except RebootDetected as e:
        # VE 2026-08-15: hard FAIL, no retry. TASK-432's fix (aeEnsureAudio's
        # DMA floor + nothrow/null-check) means a memory shortfall degrades to
        # `play FAILED` with the device alive. A reset on this path is now a
        # real defect — retrying past it is how a broken build goes green.
        fail(f"device reset during the sequence ({e}) — a reset is a hard FAIL since "
             "TASK-432: the alloc guards degrade a shortfall to `play FAILED` without "
             "resetting, so this is a genuine crash to diagnose (capture the backtrace "
             "and addr2line it), not a transient to retry past")
    except PlaybackNeverStarted as e:
        fail(f"playback never started ({e}) — DUT-measured (TASK-416 precedent): this "
             "needs a genuinely fresh boot (a real reflash), not an in-process retry, "
             "which lands inside the double-reset-detector window and reproduces the "
             "identical stuck state. Re-run run/playorder-player.")
    else:
        print(f"\nPASS: auto-advanced 5/5 real short files ({played_rows}), stopped "
              f"cleanly after the last (repeat off) — no WDT, no reset, "
              f"env=cyd2usb_player")
        ser.close()
        return 0
    return 1  # unreachable — fail() exits


if __name__ == "__main__":
    sys.exit(main())
