# serialdbg-001 (TASK-056a): inject GIT_REV from `git rev-parse`.
# TASK-681: previously appended -DGIT_REV=... to global CPPFLAGS. A -D value
# is not a file SCons' dependency scanner tracks, so on an incremental build
# only translation units that happen to recompile for OTHER reasons pick up
# the new value -- boot.cpp / cmdMisc.cpp can keep reporting a stale commit
# for many builds after HEAD moves. Write a real header instead: any TU that
# #includes it gets a proper dependency edge, so a changed hash forces a
# recompile of exactly (and only) its includers. Only rewrite the file when
# the value differs, so an unchanged hash leaves the header's mtime alone and
# the build stays incremental.
import os
import subprocess
Import("env")

try:
    rev = subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"],
        stderr=subprocess.DEVNULL
    ).decode().strip()
    dirty = subprocess.call(["git", "diff", "--quiet"],
                            stderr=subprocess.DEVNULL)
    tag = rev + ("+" if dirty else "")
except Exception:
    tag = "unknown"

# gen_build/ is gitignored (TASK-681) -- unlike gen/, it is not golden.sha256
# -gated, since this value is expected to change on every commit.
out_dir = os.path.join(env.subst("$PROJECT_DIR"), "gen_build")
out_path = os.path.join(out_dir, "git_rev.h")
new_content = (
    "// Auto-generated by scripts/inject_git_hash.py -- do not edit or commit.\n"
    "#pragma once\n"
    f'#define GIT_REV "{tag}"\n'
)

os.makedirs(out_dir, exist_ok=True)
old_content = None
if os.path.exists(out_path):
    with open(out_path, "r") as f:
        old_content = f.read()
if old_content != new_content:
    with open(out_path, "w") as f:
        f.write(new_content)
